# Generated by Django 5.0.7 on 2024-07-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_react_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='photo',
        ),
    ]
