# Generated by Django 5.0.7 on 2024-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_react_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
