# Generated by Django 5.0.7 on 2024-07-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_react_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='department',
            new_name='eventName',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='formLink',
        ),
    ]
