# Generated by Django 5.0.7 on 2024-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='fbLink',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='gitLink',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedinLink',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='eventName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='formLink',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
