# Generated by Django 5.0.7 on 2024-08-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_react_date_team_fblink_team_gitlink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='eventName',
            new_name='Event_Name',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='formLink',
            new_name='Form_Link',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='photo',
            new_name='Photo',
        ),
    ]
