# Generated by Django 5.0.7 on 2024-08-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_date_react_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='Photo',
            new_name='Poster',
        ),
    ]
