# Generated by Django 5.0.7 on 2024-08-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_photo_react_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='fbLink',
            new_name='Facebook_Link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='gitLink',
            new_name='Github_Link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='linkedinLink',
            new_name='Linkedin_Link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='photo',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='position',
            new_name='Position',
        ),
    ]
