# Generated by Django 5.0.7 on 2024-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_fblink_team_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='Poster',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
